"""
decode_sih / core / models.py
──────────────────────────────
Canonical domain models for the UPI Fraud Prevention system.

All data flowing through emitter → graph engine → pipeline → API is typed
using these Pydantic models. Strict typing prevents silent bugs and makes
every field self-documenting.

Design principles:
- Immutable after construction (model_config frozen=True where it makes sense)
- All monetary amounts are in integer PAISE (1/100 of a Rupee) to avoid
  floating-point rounding errors in financial calculations.
- UUIDs for all primary keys (not phone numbers — scammers rotate those).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, field_validator, model_validator


# ─── Enumerations ─────────────────────────────────────────────────────────────


class TransactionStatus(StrEnum):
    """Lifecycle state of a UPI transaction."""
    PENDING    = "PENDING"     # In-flight, being evaluated
    CLEARED    = "CLEARED"     # Passed risk check, settled
    FLAGGED    = "FLAGGED"     # Elevated risk, queued for manual review
    BLOCKED    = "BLOCKED"     # Intercepted before settlement
    REVERSED   = "REVERSED"   # Post-settlement reversal (chargeback)


class FraudPattern(StrEnum):
    """Structural fraud topologies detected by the graph engine."""
    FAN_OUT         = "FAN_OUT"          # 1 sender → N receivers rapidly
    FAN_IN          = "FAN_IN"           # N senders → 1 receiver (mule collector)
    SCATTER_GATHER  = "SCATTER_GATHER"   # Split → multi-hop → re-aggregate
    MULE_CHAIN      = "MULE_CHAIN"       # Linear chain of fund forwarding
    VELOCITY_ABUSE  = "VELOCITY_ABUSE"   # Abnormally high transaction velocity
    ROUND_TRIP      = "ROUND_TRIP"       # Funds returned to origin via intermediaries


class RiskVerdict(StrEnum):
    """Final risk decision issued by the pipeline."""
    CLEAR  = "CLEAR"    # Low risk — allow transaction
    FLAG   = "FLAG"     # Medium risk — allow but monitor
    BLOCK  = "BLOCK"    # High risk — intercept before settlement


class AccountType(StrEnum):
    INDIVIDUAL  = "INDIVIDUAL"
    MERCHANT    = "MERCHANT"
    BUSINESS    = "BUSINESS"
    UNKNOWN     = "UNKNOWN"


# ─── Core Domain Models ───────────────────────────────────────────────────────


class UPITransaction(BaseModel):
    """
    A single UPI payment event flowing through the system.

    Monetary amounts are stored in PAISE (integer) to ensure precision.
    """

    model_config = {"frozen": True}

    txn_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Globally unique transaction identifier (UUID v4)",
    )
    sender_id: str = Field(
        description="Sender account node ID (VPA hash or anonymised account ID)",
    )
    receiver_id: str = Field(
        description="Receiver account node ID",
    )
    amount_paise: Annotated[int, Field(ge=1, le=100_000_000_00)] = Field(
        description="Transaction amount in PAISE (1 INR = 100 PAISE). Max ₹1 crore.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of transaction initiation",
    )
    status: TransactionStatus = TransactionStatus.PENDING
    upi_ref: str | None = Field(
        default=None,
        description="Bank-assigned UPI reference number (optional)",
    )
    device_fingerprint: str | None = Field(
        default=None,
        description="Anonymised device/IP fingerprint for velocity analysis",
    )
    is_synthetic: bool = Field(
        default=False,
        description="True if this transaction was generated by the emitter (not real data)",
    )
    injected_pattern: FraudPattern | None = Field(
        default=None,
        description="If synthetic, the fraud pattern this transaction is part of (ground truth)",
    )

    @field_validator("sender_id", "receiver_id")
    @classmethod
    def ids_must_not_be_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Account IDs cannot be empty or whitespace")
        return v.strip()

    @model_validator(mode="after")
    def sender_and_receiver_must_differ(self) -> UPITransaction:
        if self.sender_id == self.receiver_id:
            raise ValueError("Sender and receiver cannot be the same account")
        return self

    @property
    def amount_rupees(self) -> float:
        """Convenience accessor for display purposes only. Never use for math."""
        return self.amount_paise / 100.0

    def __repr__(self) -> str:
        return (
            f"<TXN {self.txn_id[:8]}… "
            f"{self.sender_id[:8]}→{self.receiver_id[:8]} "
            f"₹{self.amount_rupees:.2f} {self.status}>"
        )


class Edge(BaseModel):
    """A directed, timestamped transaction link between two accounts."""
    model_config = {"frozen": True}

    txn_id: str
    target_id: str  # The "other" node (receiver if out_edge, sender if in_edge)
    amount_paise: int
    timestamp: datetime


class AccountNode(BaseModel):
    """
    A graph node representing a UPI account (sender or receiver).
    When serialized or retrieved from the GraphStore, edges are strongly typed.
    """

    account_id: str
    account_type: AccountType = AccountType.UNKNOWN
    out_edges: list[Edge] = Field(default_factory=list)
    in_edges: list[Edge] = Field(default_factory=list)
    flags: list[str] = Field(default_factory=list)
    first_seen: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_seen: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Windowed counters (reset per analysis window)
    outbound_count: int = 0        # Txns sent in current window
    inbound_count: int = 0         # Txns received in current window
    unique_receivers: set[str] = Field(default_factory=set)
    unique_senders: set[str] = Field(default_factory=set)
    total_sent_paise: int = 0
    total_received_paise: int = 0

    # Risk signals
    risk_score: float = 0.0
    is_flagged: bool = False
    is_blocked: bool = False
    flag_reasons: list[FraudPattern] = Field(default_factory=list)

    model_config = {"arbitrary_types_allowed": True}

    @property
    def out_degree(self) -> int:
        return len(self.unique_receivers)

    @property
    def in_degree(self) -> int:
        return len(self.unique_senders)


class FraudAlert(BaseModel):
    """
    A structured fraud alert emitted by the pattern detector.
    Contains a complete, auditable causal explanation.
    """

    model_config = {"frozen": True}

    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    triggered_by_txn: str = Field(description="txn_id of the transaction that completed the pattern")
    pattern: FraudPattern
    verdict: RiskVerdict
    risk_score: float = Field(ge=0.0, le=1.0)
    implicated_accounts: list[str] = Field(description="Account IDs forming the fraud subgraph")
    implicated_transactions: list[str] = Field(description="txn_ids forming the fraud subgraph")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Human-readable + machine-readable explanation
    explanation_text: str = Field(description="Plain English causal explanation for regulators")
    explanation_cypher: str | None = Field(
        default=None,
        description="Graph query (Cypher-style pseudocode) that identifies the fraud subgraph",
    )
    detection_latency_ms: float = Field(
        description="Time from transaction ingestion to alert emission (ms)"
    )
    within_sla: bool = Field(description="True if detection_latency_ms <= configured budget")

    def __repr__(self) -> str:
        sla_icon = "✅" if self.within_sla else "⚠️"
        return (
            f"<FraudAlert {self.alert_id[:8]}… "
            f"pattern={self.pattern} score={self.risk_score:.3f} "
            f"verdict={self.verdict} latency={self.detection_latency_ms:.1f}ms {sla_icon}>"
        )


class PipelineMetrics(BaseModel):
    """Running operational metrics for the stream pipeline."""

    uptime_seconds: float = 0.0
    total_transactions_processed: int = 0
    total_alerts_emitted: int = 0
    total_blocked: int = 0
    total_flagged: int = 0
    current_tps: float = 0.0
    peak_tps: float = 0.0
    avg_detection_latency_ms: float = 0.0
    p99_detection_latency_ms: float = 0.0
    sla_breach_count: int = 0
    sla_compliance_rate: float = 1.0
    graph_node_count: int = 0
    graph_edge_count: int = 0
